package hms;

import java.awt.Desktop;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Suson
 */
public class AboutUsFrame extends javax.swing.JFrame {

    /**
     * This is a constructor which initializes all the component required for
     * launching new about us frame.
     *
     */
    public AboutUsFrame() {
        Configuration config = new Configuration();
        config.setIconAndTitle(this, "About Us");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        addPatientButton = new javax.swing.JButton();
        addDoctorButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewPatientButton = new javax.swing.JButton();
        helpTextButton = new javax.swing.JButton();
        contactButton = new javax.swing.JButton();
        viewDoctorsButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        susonImage = new javax.swing.JLabel();
        prabinImage = new javax.swing.JLabel();
        pratikImage = new javax.swing.JLabel();
        susonLabel = new javax.swing.JLabel();
        pratikLabel = new javax.swing.JLabel();
        prabinLabel = new javax.swing.JLabel();
        meetTeamLabel = new javax.swing.JLabel();
        pratikHandle = new javax.swing.JLabel();
        prabinHandle = new javax.swing.JLabel();
        susonHandle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        saveMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(450, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 1080));

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        homeButton.setText(" Home Page");
        homeButton.setActionCommand("  Manage Patients");
        homeButton.setAlignmentY(0.0F);
        homeButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240))));
        homeButton.setBorderPainted(false);
        homeButton.setFocusPainted(false);
        homeButton.setFocusable(false);
        homeButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        homeButton.setMaximumSize(new java.awt.Dimension(180, 60));
        homeButton.setMinimumSize(new java.awt.Dimension(180, 60));
        homeButton.setPreferredSize(new java.awt.Dimension(180, 60));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addPatientButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addPatientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        addPatientButton.setText(" Add Patient");
        addPatientButton.setAlignmentY(0.0F);
        addPatientButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        addPatientButton.setBorderPainted(false);
        addPatientButton.setFocusPainted(false);
        addPatientButton.setFocusable(false);
        addPatientButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addPatientButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        addPatientButton.setMaximumSize(new java.awt.Dimension(180, 60));
        addPatientButton.setMinimumSize(new java.awt.Dimension(180, 60));
        addPatientButton.setPreferredSize(new java.awt.Dimension(180, 60));
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        addDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addDoctorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student (1).png"))); // NOI18N
        addDoctorButton.setText("  Add Doctor");
        addDoctorButton.setActionCommand("     Add Doctor");
        addDoctorButton.setAlignmentY(0.0F);
        addDoctorButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        addDoctorButton.setBorderPainted(false);
        addDoctorButton.setFocusPainted(false);
        addDoctorButton.setFocusable(false);
        addDoctorButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addDoctorButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        addDoctorButton.setMaximumSize(new java.awt.Dimension(180, 60));
        addDoctorButton.setMinimumSize(new java.awt.Dimension(180, 60));
        addDoctorButton.setPreferredSize(new java.awt.Dimension(180, 60));
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(363, 278));
        jPanel3.setMinimumSize(new java.awt.Dimension(363, 278));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 278));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minsss.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(180, 47));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        viewPatientButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewPatientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addDetails.png"))); // NOI18N
        viewPatientButton.setText(" View Patient");
        viewPatientButton.setAlignmentY(0.0F);
        viewPatientButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        viewPatientButton.setBorderPainted(false);
        viewPatientButton.setFocusPainted(false);
        viewPatientButton.setFocusable(false);
        viewPatientButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewPatientButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        viewPatientButton.setMaximumSize(new java.awt.Dimension(180, 60));
        viewPatientButton.setMinimumSize(new java.awt.Dimension(180, 60));
        viewPatientButton.setPreferredSize(new java.awt.Dimension(180, 60));
        viewPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientButtonActionPerformed(evt);
            }
        });

        helpTextButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpTextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manual.png"))); // NOI18N
        helpTextButton.setText("      Help Text");
        helpTextButton.setAlignmentY(0.0F);
        helpTextButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        helpTextButton.setBorderPainted(false);
        helpTextButton.setFocusPainted(false);
        helpTextButton.setFocusable(false);
        helpTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        helpTextButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        helpTextButton.setMaximumSize(new java.awt.Dimension(180, 60));
        helpTextButton.setMinimumSize(new java.awt.Dimension(180, 60));
        helpTextButton.setPreferredSize(new java.awt.Dimension(180, 60));
        helpTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpTextButtonActionPerformed(evt);
            }
        });

        contactButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N
        contactButton.setAlignmentY(0.0F);
        contactButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        contactButton.setBorderPainted(false);
        contactButton.setFocusPainted(false);
        contactButton.setFocusable(false);
        contactButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        contactButton.setLabel("      Contact Us");
        contactButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        contactButton.setMaximumSize(new java.awt.Dimension(180, 60));
        contactButton.setMinimumSize(new java.awt.Dimension(180, 60));
        contactButton.setPreferredSize(new java.awt.Dimension(180, 60));
        contactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButtonActionPerformed(evt);
            }
        });

        viewDoctorsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewDoctorsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doc.png"))); // NOI18N
        viewDoctorsButton.setText(" View Doctors");
        viewDoctorsButton.setAlignmentY(0.0F);
        viewDoctorsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        viewDoctorsButton.setBorderPainted(false);
        viewDoctorsButton.setFocusPainted(false);
        viewDoctorsButton.setFocusable(false);
        viewDoctorsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewDoctorsButton.setMargin(new java.awt.Insets(0, 14, 0, 14));
        viewDoctorsButton.setMaximumSize(new java.awt.Dimension(180, 60));
        viewDoctorsButton.setMinimumSize(new java.awt.Dimension(180, 60));
        viewDoctorsButton.setPreferredSize(new java.awt.Dimension(180, 60));
        viewDoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDoctorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDoctorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(helpTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jPanel4.setBackground(new java.awt.Color(122, 122, 122));

        susonImage.setBackground(new java.awt.Color(51, 255, 0));
        susonImage.setForeground(new java.awt.Color(153, 255, 153));
        susonImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sus.png"))); // NOI18N

        prabinImage.setBackground(new java.awt.Color(51, 255, 0));
        prabinImage.setForeground(new java.awt.Color(153, 255, 153));
        prabinImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prabin.png"))); // NOI18N

        pratikImage.setBackground(new java.awt.Color(51, 255, 0));
        pratikImage.setForeground(new java.awt.Color(153, 255, 153));
        pratikImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pratik.png"))); // NOI18N

        susonLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        susonLabel.setForeground(new java.awt.Color(255, 255, 255));
        susonLabel.setText("Suson Sapkota");

        pratikLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        pratikLabel.setForeground(new java.awt.Color(255, 255, 255));
        pratikLabel.setText("Pratik Karki");

        prabinLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        prabinLabel.setForeground(new java.awt.Color(255, 255, 255));
        prabinLabel.setText("Prabin Thapaliya");

        meetTeamLabel.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        meetTeamLabel.setForeground(new java.awt.Color(255, 255, 255));
        meetTeamLabel.setText("Meet The Team");

        pratikHandle.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        pratikHandle.setForeground(new java.awt.Color(255, 255, 255));
        pratikHandle.setText("@pratik_noob");

        prabinHandle.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        prabinHandle.setForeground(new java.awt.Color(255, 255, 255));
        prabinHandle.setText("@pthapaliya10");

        susonHandle.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        susonHandle.setForeground(new java.awt.Color(255, 255, 255));
        susonHandle.setText("@sus_on");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(meetTeamLabel)
                .addGap(603, 603, 603))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pratikImage)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pratikLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(susonImage)
                    .addComponent(susonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(prabinImage)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prabinLabel)
                        .addGap(159, 159, 159))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(pratikHandle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(susonHandle)
                .addGap(348, 348, 348)
                .addComponent(prabinHandle)
                .addGap(234, 234, 234))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(meetTeamLabel)
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(prabinImage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(prabinLabel))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(susonImage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(susonLabel)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pratikImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pratikLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pratikHandle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prabinHandle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(susonHandle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(432, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        openMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Open.png"))); // NOI18N
        openMenu.setText("Open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        jMenu1.add(openMenu);

        saveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        saveMenu.setText("Save");
        saveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenu);
        jMenu1.add(jSeparator1);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit resize.png"))); // NOI18N
        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        aboutMenu.setText("About Us");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMenu);

        helpMenu.setText("Help Text");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });
        jMenu2.add(helpMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method lunches new patient frame and hides the current frame.
     *
     * @param evt
     */
    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        // TODO add your handling code here:
        new AddPatientFrame();
        setVisible(false);

    }//GEN-LAST:event_addPatientButtonActionPerformed
    /**
     * This method lunches main frame and close the current frame after few
     * milli-seconds.
     *
     * @param evt
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        Configuration config = new Configuration();
        new MainFrame().setVisible(true);
        config.closeFrameAfer(this);

    }//GEN-LAST:event_homeButtonActionPerformed
    /**
     * This method lunches new add doctor frame and hides the current frame.
     *
     * @param evt
     */
    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButtonActionPerformed
        // TODO add your handling code here:
        new AddDoctorFrame();
        setVisible(false);
    }//GEN-LAST:event_addDoctorButtonActionPerformed
    /**
     * This method lunches new view patient frame and hides the current frame.
     *
     * @param evt
     */
    private void viewPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientButtonActionPerformed
        // TODO add your handling code here:
        new ViewPatientFrame();
        setVisible(false);
    }//GEN-LAST:event_viewPatientButtonActionPerformed
    /**
     * This frame lunches the help manual for the page within the frame.
     *
     * @param evt
     */
    private void helpTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpTextButtonActionPerformed
        // TODO add your handling code here:
        Configuration config = new Configuration();
        config.DisplayHelpPDF(this);
    }//GEN-LAST:event_helpTextButtonActionPerformed

    private void contactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactButtonActionPerformed
    /**
     * This method lunches new doctor frame and hides the current frame.
     *
     * @param evt
     */
    private void viewDoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorsButtonActionPerformed
        // TODO add your handling code here:
        new ViewDoctorsFrame();
        setVisible(false);
    }//GEN-LAST:event_viewDoctorsButtonActionPerformed

    private void saveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuActionPerformed
    /**
     * this is a file chooser which opens the file chooser.
     *
     * @param evt
     */
    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int r = chooser.showOpenDialog(openMenu);
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                Desktop.getDesktop().open(chooser.getSelectedFile());
            } catch (IOException e1) {
                JOptionPane.showMessageDialog(openMenu, "Could not open file " + chooser.getSelectedFile().getAbsolutePath());
            }
        }

    }//GEN-LAST:event_openMenuActionPerformed
    /**
     * This is menu item which closes the frame
     *
     * @param evt
     */
    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed
    /**
     * This method lunches about us frame and hides the current frame.
     *
     * @param evt
     */
    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
        new AboutUsFrame();
        setVisible(false);
    }//GEN-LAST:event_aboutMenuActionPerformed
    /**
     * This menu item which launches the help PDF inside within the program
     *
     * @param evt
     */
    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
        Configuration config = new Configuration();
        config.DisplayHelpPDF(this);
    }//GEN-LAST:event_helpMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton contactButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JButton helpTextButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel meetTeamLabel;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JLabel prabinHandle;
    private javax.swing.JLabel prabinImage;
    private javax.swing.JLabel prabinLabel;
    private javax.swing.JLabel pratikHandle;
    private javax.swing.JLabel pratikImage;
    private javax.swing.JLabel pratikLabel;
    private javax.swing.JMenuItem saveMenu;
    private javax.swing.JLabel susonHandle;
    private javax.swing.JLabel susonImage;
    private javax.swing.JLabel susonLabel;
    private javax.swing.JButton viewDoctorsButton;
    private javax.swing.JButton viewPatientButton;
    // End of variables declaration//GEN-END:variables
}
