/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Suson
 */
public class PopUpClass extends javax.swing.JFrame {

    /**
     * Initializes the popup class and its components
     */
    public PopUpClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setUndecorated(true);
        setResizable(false);

        popUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        popUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, java.awt.Color.darkGray, null));
        popUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(popUp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popUp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * This method closes the frame when clicked to the frame
     *
     * @param evt
     */
    private void popUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popUpMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_popUpMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel popUp;
    // End of variables declaration//GEN-END:variables
}
